# Generated by Django 4.2.7 on 2023-11-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estudios', models.CharField(max_length=200)),
                ('puesto_laboral', models.CharField(max_length=100)),
                ('ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_civil', models.CharField(max_length=50)),
                ('capacidades', models.TextField()),
                ('habilidades', models.TextField()),
                ('competencias', models.TextField()),
            ],
        ),
    ]
