# Generated by Django 4.2.7 on 2023-11-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ponderacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ponderacion', models.IntegerField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactores', to='about.factor')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.persona')),
                ('subfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.subfactor')),
            ],
        ),
    ]
