# Generated by Django 4.2.7 on 2023-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_factor_subfactor_resultadotest'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='Valor por defecto', max_length=100),
        ),
    ]
