# Generated by Django 4.2.7 on 2023-11-20 20:44

import about.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_persona_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default value', max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('job_position', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marital_status', models.CharField(max_length=50)),
                ('monthly_expenditure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capabilities', models.TextField()),
                ('skills', models.TextField()),
                ('competencies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('person', models.ForeignKey(default=about.models.default_person_function, on_delete=django.db.models.deletion.CASCADE, to='about.person')),
            ],
        ),
        migrations.RemoveField(
            model_name='resultadotest',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='resultadotest',
            name='subfactor',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='ponderacion',
            new_name='weighting',
        ),
        migrations.RenameField(
            model_name='subfactor',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subfactor',
            old_name='ponderacion',
            new_name='weighting',
        ),
        migrations.AlterField(
            model_name='subfactor',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactors', to='about.factor'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='ResultadoTest',
        ),
        migrations.AddField(
            model_name='testresult',
            name='subfactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.subfactor'),
        ),
    ]
